#version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: ${POSTGRES_DB}
    secrets:
      - postgres_password

  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    secrets:
      - mongo_password

  user-service:
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:$${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

  auth-service:
    environment:
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - jwt_secret

  api-gateway:
    environment:
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - jwt_secret

  contact-service:
    environment:
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS_FILE: /run/secrets/email_password
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
    secrets:
      - email_password

  payment-service:
    environment:
      STRIPE_SECRET_KEY_FILE: /run/secrets/stripe_secret
      PAYPAL_CLIENT_SECRET_FILE: /run/secrets/paypal_secret
      TRANSBANK_SECRET_KEY_FILE: /run/secrets/transbank_secret
    secrets:
      - stripe_secret
      - paypal_secret
      - transbank_secret

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  mongo_password:
    file: ./secrets/mongo_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  email_password:
    file: ./secrets/email_password.txt
  stripe_secret:
    file: ./secrets/stripe_secret.txt
  paypal_secret:
    file: ./secrets/paypal_secret.txt
  transbank_secret:
    file: ./secrets/transbank_secret.txt