[build]
builder = "DOCKERFILE"
dockerfilePath = "microservices/api-gateway/Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 100
startCommand = "node src/server.js"
