[build]
builder = "DOCKERFILE"
dockerfilePath = "microservices/api-gateway/Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100
startCommand = "node src/server.js"
# Last updated: 2025-11-26T19:18:57Z
