
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.args]
SERVICE_NAME = "order-service"
SERVICE_PORT = "3004"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300
startCommand = "node src/server.js"
