
[build]
builder = "NIXPACKS"
watchPatterns = ["microservices/user-service/src/**", "microservices/user-service/package*.json"]

[build.args]
SERVICE_NAME = "user-service"
SERVICE_PORT = "3002"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300
